create extension if not exists pgcrypto;

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  "desc" text not null default '',
  date date not null default current_date,
  loc text not null default '',
  project_title text not null default '',
  attendee_name text not null default '',
  status text not null default 'active',
  photos integer not null default 0,
  reviews jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.media_items (
  id uuid primary key default gen_random_uuid(),
  event_id bigint not null references public.events(id) on delete cascade,
  event text not null,
  date date not null default current_date,
  label text not null,
  tone text not null default 'ocean',
  type text not null check (type in ('image', 'video')),
  source_type text not null default 'upload',
  url text not null,
  storage_path text,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.events enable row level security;
alter table public.media_items enable row level security;

drop policy if exists "Public read events" on public.events;
create policy "Public read events"
on public.events for select
to anon, authenticated
using (true);

drop policy if exists "Public insert events" on public.events;
create policy "Public insert events"
on public.events for insert
to anon, authenticated
with check (true);

drop policy if exists "Public update events" on public.events;
create policy "Public update events"
on public.events for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Public delete events" on public.events;
create policy "Public delete events"
on public.events for delete
to anon, authenticated
using (true);

drop policy if exists "Public read media" on public.media_items;
create policy "Public read media"
on public.media_items for select
to anon, authenticated
using (true);

drop policy if exists "Public insert media" on public.media_items;
create policy "Public insert media"
on public.media_items for insert
to anon, authenticated
with check (true);

drop policy if exists "Public update media" on public.media_items;
create policy "Public update media"
on public.media_items for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Public delete media" on public.media_items;
create policy "Public delete media"
on public.media_items for delete
to anon, authenticated
using (true);

insert into storage.buckets (id, name, public)
values ('event-media', 'event-media', true)
on conflict (id) do nothing;

drop policy if exists "Public read event media" on storage.objects;
create policy "Public read event media"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'event-media');

drop policy if exists "Public upload event media" on storage.objects;
create policy "Public upload event media"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'event-media');

drop policy if exists "Public update event media" on storage.objects;
create policy "Public update event media"
on storage.objects for update
to anon, authenticated
using (bucket_id = 'event-media')
with check (bucket_id = 'event-media');

drop policy if exists "Public delete event media" on storage.objects;
create policy "Public delete event media"
on storage.objects for delete
to anon, authenticated
using (bucket_id = 'event-media');
